// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "product_dense_ap_fixed_ap_fixed_ap_fixed_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic product_dense_ap_fixed_ap_fixed_ap_fixed_s::ap_const_logic_1 = sc_dt::Log_1;
const bool product_dense_ap_fixed_ap_fixed_ap_fixed_s::ap_const_boolean_1 = true;
const sc_lv<32> product_dense_ap_fixed_ap_fixed_ap_fixed_s::ap_const_lv32_2 = "10";
const sc_lv<32> product_dense_ap_fixed_ap_fixed_ap_fixed_s::ap_const_lv32_11 = "10001";
const sc_logic product_dense_ap_fixed_ap_fixed_ap_fixed_s::ap_const_logic_0 = sc_dt::Log_0;

product_dense_ap_fixed_ap_fixed_ap_fixed_s::product_dense_ap_fixed_ap_fixed_ap_fixed_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    myproject_mul_mul_16s_16s_18_1_1_U520 = new myproject_mul_mul_16s_16s_18_1_1<1,1,16,16,18>("myproject_mul_mul_16s_16s_18_1_1_U520");
    myproject_mul_mul_16s_16s_18_1_1_U520->din0(w_V);
    myproject_mul_mul_16s_16s_18_1_1_U520->din1(a_V);
    myproject_mul_mul_16s_16s_18_1_1_U520->dout(r_V_fu_41_p2);

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( r_V_fu_41_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "product_dense_ap_fixed_ap_fixed_ap_fixed_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_V, "(port)a_V");
    sc_trace(mVcdFile, w_V, "(port)w_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, r_V_fu_41_p2, "r_V_fu_41_p2");
#endif

    }
}

product_dense_ap_fixed_ap_fixed_ap_fixed_s::~product_dense_ap_fixed_ap_fixed_ap_fixed_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete myproject_mul_mul_16s_16s_18_1_1_U520;
}

void product_dense_ap_fixed_ap_fixed_ap_fixed_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void product_dense_ap_fixed_ap_fixed_ap_fixed_s::thread_ap_return() {
    ap_return = r_V_fu_41_p2.read().range(17, 2);
}

}

