Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,14>
    ReuseFactor: 1024
    Strategy: Resource
IOType: io_stream
InputData: null
KerasModel: !keras_model 'LARGE_CNN_COSIM_TEST/keras_model.h5'
OutputDir: LARGE_CNN_COSIM_TEST
OutputPredictions: null
ProjectName: myproject
Stamp: cA6ff1Cb
XilinxPart: xczu9eg-ffvb1156-2-e
