// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module product_dense_ap_fixed_ap_fixed_ap_fixed_s (
        ap_ready,
        a_V,
        w_V,
        ap_return
);


output   ap_ready;
input  [15:0] a_V;
input  [15:0] w_V;
output  [15:0] ap_return;

wire  signed [17:0] r_V_fu_41_p2;

myproject_mul_mul_16s_16s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 18 ))
myproject_mul_mul_16s_16s_18_1_1_U520(
    .din0(w_V),
    .din1(a_V),
    .dout(r_V_fu_41_p2)
);

assign ap_ready = 1'b1;

assign ap_return = {{r_V_fu_41_p2[17:2]}};

endmodule //product_dense_ap_fixed_ap_fixed_ap_fixed_s
